"""Initial MarkaRadar database schema.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-02

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column(
            "telegram_id",
            sa.BigInteger(),
            nullable=False,
        ),
        sa.Column(
            "username",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "first_name",
            sa.String(length=128),
            nullable=False,
        ),
        sa.Column(
            "last_name",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "language_code",
            sa.String(length=10),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column(
            "last_activity",
            sa.DateTime(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "telegram_id",
            name=op.f("pk_users"),
        ),
    )

    op.create_index(
        op.f("ix_users_username"),
        "users",
        ["username"],
        unique=False,
    )

    op.create_index(
        op.f("ix_users_last_activity"),
        "users",
        ["last_activity"],
        unique=False,
    )

    op.create_table(
        "brands",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=128),
            nullable=False,
        ),
        sa.Column(
            "normalized_name",
            sa.String(length=128),
            nullable=False,
        ),
        sa.Column(
            "aliases",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "country",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "logo_url",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_brands"),
        ),
        sa.UniqueConstraint(
            "name",
            name=op.f("uq_brands_name"),
        ),
    )

    op.create_index(
        op.f("ix_brands_name"),
        "brands",
        ["name"],
        unique=False,
    )

    op.create_index(
        op.f("ix_brands_normalized_name"),
        "brands",
        ["normalized_name"],
        unique=False,
    )

    op.create_table(
        "categories",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=128),
            nullable=False,
        ),
        sa.Column(
            "normalized_name",
            sa.String(length=128),
            nullable=False,
        ),
        sa.Column(
            "parent_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f(
                "fk_categories_parent_id_categories"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_categories"),
        ),
        sa.UniqueConstraint(
            "name",
            name=op.f("uq_categories_name"),
        ),
    )

    op.create_index(
        op.f("ix_categories_name"),
        "categories",
        ["name"],
        unique=False,
    )

    op.create_index(
        op.f("ix_categories_normalized_name"),
        "categories",
        ["normalized_name"],
        unique=False,
    )

    op.create_index(
        op.f("ix_categories_parent_id"),
        "categories",
        ["parent_id"],
        unique=False,
    )

    op.create_table(
        "products",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "normalized_name",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "brand_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "category_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "barcode",
            sa.String(length=32),
            nullable=True,
        ),
        sa.Column(
            "package_value",
            sa.Numeric(
                precision=10,
                scale=3,
            ),
            nullable=True,
        ),
        sa.Column(
            "package_unit",
            sa.String(length=20),
            nullable=True,
        ),
        sa.Column(
            "subtype",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "image_url",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "keywords",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f(
                "fk_products_brand_id_brands"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f(
                "fk_products_category_id_categories"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_products"),
        ),
        sa.UniqueConstraint(
            "barcode",
            name=op.f("uq_products_barcode"),
        ),
    )

    op.create_index(
        op.f("ix_products_name"),
        "products",
        ["name"],
        unique=False,
    )

    op.create_index(
        op.f("ix_products_normalized_name"),
        "products",
        ["normalized_name"],
        unique=False,
    )

    op.create_index(
        op.f("ix_products_brand_id"),
        "products",
        ["brand_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_products_category_id"),
        "products",
        ["category_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_products_barcode"),
        "products",
        ["barcode"],
        unique=False,
    )

    op.create_index(
        op.f("ix_products_subtype"),
        "products",
        ["subtype"],
        unique=False,
    )

    op.create_index(
        op.f("ix_products_is_active"),
        "products",
        ["is_active"],
        unique=False,
    )

    op.create_index(
        op.f("ix_products_updated_at"),
        "products",
        ["updated_at"],
        unique=False,
    )

    op.create_index(
        "ix_products_brand_category",
        "products",
        ["brand_id", "category_id"],
        unique=False,
    )

    op.create_index(
        "ix_products_active_normalized_name",
        "products",
        ["is_active", "normalized_name"],
        unique=False,
    )

    op.create_table(
        "product_relations",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "source_category_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "target_category_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "target_subtype",
            sa.String(length=128),
            nullable=False,
        ),
        sa.Column(
            "compatibility_score",
            sa.Numeric(
                precision=4,
                scale=3,
            ),
            nullable=False,
        ),
        sa.Column(
            "explanation",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "compatibility_score >= 0 "
                "AND compatibility_score <= 1"
            ),
            name=op.f(
                "ck_product_relations_"
                "compatibility_score_0_1"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["source_category_id"],
            ["categories.id"],
            name=op.f(
                "fk_product_relations_"
                "source_category_id_categories"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_category_id"],
            ["categories.id"],
            name=op.f(
                "fk_product_relations_"
                "target_category_id_categories"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_product_relations"),
        ),
        sa.UniqueConstraint(
            "source_category_id",
            "target_category_id",
            "target_subtype",
            name="uq_product_relation",
        ),
    )

    op.create_index(
        op.f(
            "ix_product_relations_"
            "source_category_id"
        ),
        "product_relations",
        ["source_category_id"],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_product_relations_"
            "target_category_id"
        ),
        "product_relations",
        ["target_category_id"],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_product_relations_target_subtype"
        ),
        "product_relations",
        ["target_subtype"],
        unique=False,
    )

    op.create_table(
        "ratings",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.BigInteger(),
            nullable=False,
        ),
        sa.Column(
            "product_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "score",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "score >= 1 AND score <= 10",
            name=op.f(
                "ck_ratings_score_1_10"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f(
                "fk_ratings_product_id_products"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.telegram_id"],
            name=op.f(
                "fk_ratings_user_id_users"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_ratings"),
        ),
        sa.UniqueConstraint(
            "user_id",
            "product_id",
            name="uq_rating_user_product",
        ),
    )

    op.create_index(
        op.f("ix_ratings_user_id"),
        "ratings",
        ["user_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_ratings_product_id"),
        "ratings",
        ["product_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_ratings_updated_at"),
        "ratings",
        ["updated_at"],
        unique=False,
    )

    op.create_table(
        "reviews",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.BigInteger(),
            nullable=False,
        ),
        sa.Column(
            "product_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "text",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "moderation_status",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f(
                "fk_reviews_product_id_products"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.telegram_id"],
            name=op.f(
                "fk_reviews_user_id_users"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_reviews"),
        ),
        sa.UniqueConstraint(
            "user_id",
            "product_id",
            name="uq_review_user_product",
        ),
    )

    op.create_index(
        op.f("ix_reviews_user_id"),
        "reviews",
        ["user_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_reviews_product_id"),
        "reviews",
        ["product_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_reviews_moderation_status"),
        "reviews",
        ["moderation_status"],
        unique=False,
    )

    op.create_index(
        op.f("ix_reviews_updated_at"),
        "reviews",
        ["updated_at"],
        unique=False,
    )

    op.create_table(
        "price_observations",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "product_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "retailer_name",
            sa.String(length=128),
            nullable=False,
        ),
        sa.Column(
            "region",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "price",
            sa.Numeric(
                precision=12,
                scale=2,
            ),
            nullable=False,
        ),
        sa.Column(
            "source_url",
            sa.String(length=1000),
            nullable=True,
        ),
        sa.Column(
            "observed_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "price > 0",
            name=op.f(
                "ck_price_observations_price_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f(
                "fk_price_observations_"
                "product_id_products"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f(
                "pk_price_observations"
            ),
        ),
    )

    op.create_index(
        op.f(
            "ix_price_observations_product_id"
        ),
        "price_observations",
        ["product_id"],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_price_observations_retailer_name"
        ),
        "price_observations",
        ["retailer_name"],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_price_observations_region"
        ),
        "price_observations",
        ["region"],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_price_observations_observed_at"
        ),
        "price_observations",
        ["observed_at"],
        unique=False,
    )

    op.create_table(
        "product_aliases",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "product_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "alias",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "normalized_alias",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f(
                "fk_product_aliases_"
                "product_id_products"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_product_aliases"),
        ),
        sa.UniqueConstraint(
            "product_id",
            "alias",
            name="uq_product_alias",
        ),
    )

    op.create_index(
        op.f(
            "ix_product_aliases_product_id"
        ),
        "product_aliases",
        ["product_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_product_aliases_alias"),
        "product_aliases",
        ["alias"],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_product_aliases_normalized_alias"
        ),
        "product_aliases",
        ["normalized_alias"],
        unique=False,
    )

    op.create_table(
        "search_history",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.BigInteger(),
            nullable=False,
        ),
        sa.Column(
            "query_text",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "normalized_query",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "selected_product_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "selected_category_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["selected_category_id"],
            ["categories.id"],
            name=op.f(
                "fk_search_history_"
                "selected_category_id_categories"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["selected_product_id"],
            ["products.id"],
            name=op.f(
                "fk_search_history_"
                "selected_product_id_products"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.telegram_id"],
            name=op.f(
                "fk_search_history_user_id_users"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_search_history"),
        ),
    )

    op.create_index(
        op.f("ix_search_history_user_id"),
        "search_history",
        ["user_id"],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_search_history_normalized_query"
        ),
        "search_history",
        ["normalized_query"],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_search_history_selected_product_id"
        ),
        "search_history",
        ["selected_product_id"],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_search_history_selected_category_id"
        ),
        "search_history",
        ["selected_category_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_search_history_created_at"),
        "search_history",
        ["created_at"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        op.f("ix_search_history_created_at"),
        table_name="search_history",
    )
    op.drop_index(
        op.f(
            "ix_search_history_selected_category_id"
        ),
        table_name="search_history",
    )
    op.drop_index(
        op.f(
            "ix_search_history_selected_product_id"
        ),
        table_name="search_history",
    )
    op.drop_index(
        op.f(
            "ix_search_history_normalized_query"
        ),
        table_name="search_history",
    )
    op.drop_index(
        op.f("ix_search_history_user_id"),
        table_name="search_history",
    )
    op.drop_table("search_history")

    op.drop_index(
        op.f(
            "ix_product_aliases_normalized_alias"
        ),
        table_name="product_aliases",
    )
    op.drop_index(
        op.f("ix_product_aliases_alias"),
        table_name="product_aliases",
    )
    op.drop_index(
        op.f(
            "ix_product_aliases_product_id"
        ),
        table_name="product_aliases",
    )
    op.drop_table("product_aliases")

    op.drop_index(
        op.f(
            "ix_price_observations_observed_at"
        ),
        table_name="price_observations",
    )
    op.drop_index(
        op.f(
            "ix_price_observations_region"
        ),
        table_name="price_observations",
    )
    op.drop_index(
        op.f(
            "ix_price_observations_retailer_name"
        ),
        table_name="price_observations",
    )
    op.drop_index(
        op.f(
            "ix_price_observations_product_id"
        ),
        table_name="price_observations",
    )
    op.drop_table("price_observations")

    op.drop_index(
        op.f("ix_reviews_updated_at"),
        table_name="reviews",
    )
    op.drop_index(
        op.f("ix_reviews_moderation_status"),
        table_name="reviews",
    )
    op.drop_index(
        op.f("ix_reviews_product_id"),
        table_name="reviews",
    )
    op.drop_index(
        op.f("ix_reviews_user_id"),
        table_name="reviews",
    )
    op.drop_table("reviews")

    op.drop_index(
        op.f("ix_ratings_updated_at"),
        table_name="ratings",
    )
    op.drop_index(
        op.f("ix_ratings_product_id"),
        table_name="ratings",
    )
    op.drop_index(
        op.f("ix_ratings_user_id"),
        table_name="ratings",
    )
    op.drop_table("ratings")

    op.drop_index(
        op.f(
            "ix_product_relations_target_subtype"
        ),
        table_name="product_relations",
    )
    op.drop_index(
        op.f(
            "ix_product_relations_"
            "target_category_id"
        ),
        table_name="product_relations",
    )
    op.drop_index(
        op.f(
            "ix_product_relations_"
            "source_category_id"
        ),
        table_name="product_relations",
    )
    op.drop_table("product_relations")

    op.drop_index(
        "ix_products_active_normalized_name",
        table_name="products",
    )
    op.drop_index(
        "ix_products_brand_category",
        table_name="products",
    )
    op.drop_index(
        op.f("ix_products_updated_at"),
        table_name="products",
    )
    op.drop_index(
        op.f("ix_products_is_active"),
        table_name="products",
    )
    op.drop_index(
        op.f("ix_products_subtype"),
        table_name="products",
    )
    op.drop_index(
        op.f("ix_products_barcode"),
        table_name="products",
    )
    op.drop_index(
        op.f("ix_products_category_id"),
        table_name="products",
    )
    op.drop_index(
        op.f("ix_products_brand_id"),
        table_name="products",
    )
    op.drop_index(
        op.f("ix_products_normalized_name"),
        table_name="products",
    )
    op.drop_index(
        op.f("ix_products_name"),
        table_name="products",
    )
    op.drop_table("products")

    op.drop_index(
        op.f("ix_categories_parent_id"),
        table_name="categories",
    )
    op.drop_index(
        op.f("ix_categories_normalized_name"),
        table_name="categories",
    )
    op.drop_index(
        op.f("ix_categories_name"),
        table_name="categories",
    )
    op.drop_table("categories")

    op.drop_index(
        op.f("ix_brands_normalized_name"),
        table_name="brands",
    )
    op.drop_index(
        op.f("ix_brands_name"),
        table_name="brands",
    )
    op.drop_table("brands")

    op.drop_index(
        op.f("ix_users_last_activity"),
        table_name="users",
    )
    op.drop_index(
        op.f("ix_users_username"),
        table_name="users",
    )
    op.drop_table("users")
